name: Render Markdown

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.pdf'
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.pdf'    

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install pystache
      - name: Render Markdown
        run: |
          python ./scripts/mustache.py ./documents/templates/doctemplate.tpl ./documents/json/doc1.json ./documents/doc1.md
      - name: Add all changes to the repo.
        run: |
          git add -A
          git commit -m "Rendered Markdown"
      - name: Push changes
        run: |
          git push
